import CrudPage from "./CrudPage";

const activityTypeOptions = [
  { value: "REFERRAL", label: "Referral" },
  { value: "SALARY_CREDIT", label: "Salary Credit" },
  { value: "ACCOUNT_ANNIVERSARY", label: "Account Anniversary" },
  { value: "PROFILE_COMPLETION", label: "Profile Completion" },
  { value: "FIRST_10_UNIQUE_MERCHANTS", label: "First 10 Unique Merchants" },
  { value: "PROMOTIONAL_EVENT", label: "Promotional Event" },
  { value: "HOLIDAY_BONUS", label: "Holiday Bonus" },
  { value: "MONTHLY_ACTIVE_USER", label: "Monthly Active User" }
];

const fieldDefs = [
  { 
    name: "userId", 
    label: "User ID", 
    type: "number", 
    required: true 
  },
  {
    name: "activityType",
    label: "Activity Type",
    type: "select",
    required: true,
    options: activityTypeOptions,
    placeholder: "Select activity type"
  }
  // activityDate is auto-generated by backend
];

export default function Activities() {
  return (
    <CrudPage
      title="Activity"
      path="/activities"
      idKey="activityId"
      fieldDefs={fieldDefs}
    />
  );
}
